name: build and test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  buildandtest:
    name: Build and Test on Go ${{matrix.go}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 'stable', 'oldstable' ]

    steps:
      - name: Prepare
        run: |
          sudo nft add table ip filter
          sudo nft add table ip mangle
          sudo nft add table ip nat
          sudo nft add table ip6 filter
          sudo nft add table ip6 mangle
          sudo nft add table ip6 nat

      - name: Set up Go ${{matrix.go}}
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # pin@v4
        with:
          go-version: ${{matrix.go}}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # pin@v3

      - name: Test Go packages
        run: |
          go test -v -exec sudo -race -p=1 -count=1 ./...
          go test -v -race -p=1 -count=1 ./...
