name: build and test
on:
  push:
    branches:
      - master
      - develop

jobs:

  buildandtest:
    name: Build and Test on Go ${{matrix.go}}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go: [ '1.19', '1.18' ]
    steps:
      - name: Prepare
        run: |
          sudo nft add table ip filter
          sudo nft add table ip mangle
          sudo nft add table ip nat
          sudo nft add table ip6 filter
          sudo nft add table ip6 mangle
          sudo nft add table ip6 nat

      - name: Set up Go ${{matrix.go}}
        uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # pin@v3
        with:
          go-version: ${{matrix.go}}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Test Go packages as root
        run: go test -v -p 1 -race  -exec sudo ./...

      - name: Test Go packages as ordinary user
        run: go test -v -p 1 -race ./...
